sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-533.pdf --upload --lsstdoc LDM-533.tex --env=travis --ltd-product ldm-533"
env:
  global:
    # LSST the Docs credentials
    - secure: "EvGZu/sKA9D1Nd9J2af2EAgdp7gG+n9OOKxgZzoau2xXFdM66EhAGAvgmNhcxLfxCglRQdK6tLlBb7J8+xiLWYWcjHkVWwwF1YfMXzSx44DD5xfJcNbkqRLsDl1xkfSaKcwJusS9lXUEgAO4R08cVbvLCZWkGMr7RD1nvH6yorZYL+rKeUHXqv5VDcXo4MlACodwHTyaT+Z2iVOzq61aJkTnOQxEvYDqQmZjz86kCDbL88hiPcutuapNlsIS4dPm4Lb+882lv2Ogxd/wn6T6FRNFWoiowJAJb16tt3srLxKYBz5kSaPIdhl8JKI1Rz4sMTvP9ShQxvGig0KEIRPkj+UTHm55/An+h7XSLrJXA6aU6txWpZFg2P8fTPZ2lF/w8M6C+6XjofaSZvijorBIMrvzb6KWHdSsK6yH/4ZnBCOwKYH+mA1IT3PL1iaCaeiiY+fZLwMrZWClsyduE1mOSF1G4opo5PfnkgkDamLv4vOiSN6K1EhZEH3lx7pn77iSoQ3IYzgZty1btQ/zyaBnTBCEAkc3M9M8vCoKp41UYR7XX/PSQEmyRiyyO7lqsS4KwRYrv+0OdNicrz9rvfzz4x0FTHYvgeggHoFDoF24Z31KYcFtXxeTg4fyuRfDLqv8BgWrjk6QER/vUUbKeFtuIJdCILknvF9Km4qyIQOIdNc="
    - secure: "Rr3FQPd8b0iSnTpzn4NW/6PtsvDdXjgcjTFg4NswjuOPaw/v2uZSbj9pbXbZwBSWXqqhm6A4pb3e6MqUnVgtrwviCz1pN8f8LN0SbxWkbEBXg/8yLuPLeem/rQ6snjs3uxrfVXm4PlfBC56wHprx+mrIqHzPPWE1Q5mA5Dtkd3YP/whzUyUzjPKLjlLLuqP5vNgNdX/6TA38AfXYaokItmt5y21NyA+yIOCaso8oPItGGrzAXkNi+a5BmKCAHp8c7kik/HBYP/er1Ifi45nYTlUsNWE59++aUHl4B7CFl//VDdW6xI6vdmJX4yOBvSiUJiQYpkPAO5pnXfaVYEoc6TauK6YRlvVAlbbdFjdkVRIVuvzwAavPrEFXzJQbnW5Z7cwUuoaJn5CmSX3TsfkzbSf9O0e1cvjBsU073S7/8x8+jZuFLx0cP+gGlAnuYiBewfw0Y1ymszTuLinzvUNjJxDJuXrpMfk2ucSPWw/OUCD5pEiFOBpnDh6tTiQq0TfGJC4Brg6IMzJQtFLWDHfjyeqskf3AcKtdJTJz+TCp/y5tiFwsqqOHDZBXHA5/+wn4VgSJh8IqQGftuvdMgfMl7JqFanAF/PRxaBK3ieyEX6vMv7Gs0NSgV6WtVQORE8Dd4nt9eeVRLLzElf7DcA6wwK8AsEqDIE7pLQ1UPjvtiJ0="
